name: docker-build

on:
  push:
    branches: [cht-s3-logs-AREMAC-4643]
  # Also trigger on release created event
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create env var for docker tag
        run: echo "TAG=$(date +%s)" >> "$GITHUB_ENV"
      - name: Create env var for git sha tag
        run: echo "HASH=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Create env var for ECR repo
        run:  echo "ECR_REPOSITORY=inspec-profile-aws-mod" >> "$GITHUB_ENV"
      - name: Configure AWS Credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
        uses: aws-actions/configure-aws-credentials@v1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build the Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: docker build . --file Dockerfile --tag $ECR_REGISTRY/$ECR_REPOSITORY:s3-test
      - name: Push docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
